package Vista;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;

/**
 *
 * @author Jose Angel Gonzalez Molina
 */
public class VentanaPrincipal extends javax.swing.JFrame {

	
	/**
	 * Creates new form VentanaPrincipal
	 */
	public VentanaPrincipal() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelIdentificacion = new javax.swing.JPanel();
        imgIdent = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        labelContrasena = new javax.swing.JLabel();
        textFieldUsuario = new javax.swing.JTextField();
        textFieldContrasena = new javax.swing.JPasswordField();
        btConectarse = new javax.swing.JButton();
        PanelInicio = new javax.swing.JPanel();
        imgSocio = new javax.swing.JLabel();
        imgBeneficiario = new javax.swing.JLabel();
        imgVoluntario = new javax.swing.JLabel();
        imgBolsaTrabajo = new javax.swing.JLabel();
        labelSocio = new javax.swing.JLabel();
        labelBeneficiario = new javax.swing.JLabel();
        labelVoluntario = new javax.swing.JLabel();
        labelBolsaTrabajo = new javax.swing.JLabel();
        PanelSocio = new javax.swing.JPanel();
        PanelBeneficiario = new javax.swing.JPanel();
        separadorBeneficiario = new javax.swing.JSeparator();
        labBMain = new javax.swing.JLabel();
        senalaBeneficiario = new javax.swing.JLabel();
        labSBenef = new javax.swing.JLabel();
        imgNBenef = new javax.swing.JLabel();
        labNBenef = new javax.swing.JLabel();
        imgBBuscar = new javax.swing.JLabel();
        labBBuscar = new javax.swing.JLabel();
        PanelVoluntario = new javax.swing.JPanel();
        separadorVoluntario = new javax.swing.JSeparator();
        labVMain = new javax.swing.JLabel();
        senalaVoluntario = new javax.swing.JLabel();
        labSVolunt = new javax.swing.JLabel();
        imgNVolunt = new javax.swing.JLabel();
        imgVBuscar = new javax.swing.JLabel();
        imgContab = new javax.swing.JLabel();
        imgAyuda = new javax.swing.JLabel();
        labVBuscar = new javax.swing.JLabel();
        labAyuda = new javax.swing.JLabel();
        labContab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Diaketas Manage");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(135, 170, 235));
        setResizable(false);

        PanelIdentificacion.setBackground(new java.awt.Color(255, 254, 254));
        PanelIdentificacion.setPreferredSize(new java.awt.Dimension(888, 450));

        imgIdent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/Acceso_Usuarios.jpg"))); // NOI18N

        labelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 0, 0));
        labelTitulo.setText("BIENVENIDO A DIAKETAS");

        labelUsuario.setText("USUARIO");

        labelContrasena.setText("CONTRASEÑA");

        textFieldUsuario.setText("Usuario");

        btConectarse.setFont(new java.awt.Font("Lucida Grande", 0, 13)); // NOI18N
        btConectarse.setText("Entrar");

        org.jdesktop.layout.GroupLayout PanelIdentificacionLayout = new org.jdesktop.layout.GroupLayout(PanelIdentificacion);
        PanelIdentificacion.setLayout(PanelIdentificacionLayout);
        PanelIdentificacionLayout.setHorizontalGroup(
            PanelIdentificacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelIdentificacionLayout.createSequentialGroup()
                .addContainerGap(515, Short.MAX_VALUE)
                .add(labelTitulo)
                .add(104, 104, 104))
            .add(PanelIdentificacionLayout.createSequentialGroup()
                .add(PanelIdentificacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PanelIdentificacionLayout.createSequentialGroup()
                        .add(476, 476, 476)
                        .add(PanelIdentificacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(labelUsuario)
                            .add(labelContrasena))
                        .add(25, 25, 25)
                        .add(PanelIdentificacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(textFieldUsuario, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .add(textFieldContrasena)))
                    .add(PanelIdentificacionLayout.createSequentialGroup()
                        .add(545, 545, 545)
                        .add(btConectarse))
                    .add(PanelIdentificacionLayout.createSequentialGroup()
                        .add(53, 53, 53)
                        .add(imgIdent)))
                .addContainerGap())
        );
        PanelIdentificacionLayout.setVerticalGroup(
            PanelIdentificacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelIdentificacionLayout.createSequentialGroup()
                .add(PanelIdentificacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PanelIdentificacionLayout.createSequentialGroup()
                        .add(112, 112, 112)
                        .add(imgIdent))
                    .add(PanelIdentificacionLayout.createSequentialGroup()
                        .add(88, 88, 88)
                        .add(labelTitulo)
                        .add(106, 106, 106)
                        .add(PanelIdentificacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(labelUsuario)
                            .add(textFieldUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(PanelIdentificacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(textFieldContrasena, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(labelContrasena))
                        .add(18, 18, 18)
                        .add(btConectarse)))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        PanelInicio.setBackground(new java.awt.Color(255, 255, 255));
        PanelInicio.setPreferredSize(new java.awt.Dimension(888, 450));

        imgSocio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/socio.png"))); // NOI18N

        imgBeneficiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/bene.png"))); // NOI18N

        imgVoluntario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/imgVolunt.jpg"))); // NOI18N

        imgBolsaTrabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/imgBolsa.jpg"))); // NOI18N

        labelSocio.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelSocio.setText("SOCIOS");

        labelBeneficiario.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelBeneficiario.setText("BENEFICIARIOS");

        labelVoluntario.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelVoluntario.setText("VOLUNTARIOS");

        labelBolsaTrabajo.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelBolsaTrabajo.setText("BOLSA DE TRABAJO");

        org.jdesktop.layout.GroupLayout PanelInicioLayout = new org.jdesktop.layout.GroupLayout(PanelInicio);
        PanelInicio.setLayout(PanelInicioLayout);
        PanelInicioLayout.setHorizontalGroup(
            PanelInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelInicioLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(PanelInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, labelBolsaTrabajo)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, PanelInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(labelBeneficiario)
                        .add(imgBolsaTrabajo)))
                .add(181, 181, 181))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, PanelInicioLayout.createSequentialGroup()
                .add(PanelInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PanelInicioLayout.createSequentialGroup()
                        .add(170, 170, 170)
                        .add(PanelInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(imgVoluntario)
                            .add(PanelInicioLayout.createSequentialGroup()
                                .add(6, 6, 6)
                                .add(labelVoluntario))))
                    .add(PanelInicioLayout.createSequentialGroup()
                        .add(206, 206, 206)
                        .add(labelSocio))
                    .add(PanelInicioLayout.createSequentialGroup()
                        .add(160, 160, 160)
                        .add(imgSocio)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 290, Short.MAX_VALUE)
                .add(imgBeneficiario)
                .add(155, 155, 155))
        );
        PanelInicioLayout.setVerticalGroup(
            PanelInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelInicioLayout.createSequentialGroup()
                .add(46, 46, 46)
                .add(PanelInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(PanelInicioLayout.createSequentialGroup()
                        .add(imgBeneficiario)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labelBeneficiario)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(imgBolsaTrabajo))
                    .add(PanelInicioLayout.createSequentialGroup()
                        .add(imgSocio)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labelSocio)
                        .add(48, 48, 48)
                        .add(imgVoluntario)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PanelInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labelVoluntario)
                    .add(labelBolsaTrabajo))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        PanelSocio.setBackground(new java.awt.Color(255, 255, 255));
        PanelSocio.setPreferredSize(new java.awt.Dimension(560, 341));

        org.jdesktop.layout.GroupLayout PanelSocioLayout = new org.jdesktop.layout.GroupLayout(PanelSocio);
        PanelSocio.setLayout(PanelSocioLayout);
        PanelSocioLayout.setHorizontalGroup(
            PanelSocioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 954, Short.MAX_VALUE)
        );
        PanelSocioLayout.setVerticalGroup(
            PanelSocioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 477, Short.MAX_VALUE)
        );

        PanelBeneficiario.setBackground(new java.awt.Color(255, 255, 255));

        labBMain.setFont(new java.awt.Font("Lucida Sans", 0, 13)); // NOI18N
        labBMain.setForeground(new java.awt.Color(0, 0, 255));
        labBMain.setText("DIAKETAS");

        senalaBeneficiario.setForeground(new java.awt.Color(153, 153, 153));
        senalaBeneficiario.setText(">");

        labSBenef.setText("Beneficiarios");

        imgNBenef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/usu.png"))); // NOI18N

        labNBenef.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labNBenef.setText("NUEVO BENEFICIARIO");

        imgBBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/lupa (1).png"))); // NOI18N

        labBBuscar.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labBBuscar.setText("BUSCAR");

        org.jdesktop.layout.GroupLayout PanelBeneficiarioLayout = new org.jdesktop.layout.GroupLayout(PanelBeneficiario);
        PanelBeneficiario.setLayout(PanelBeneficiarioLayout);
        PanelBeneficiarioLayout.setHorizontalGroup(
            PanelBeneficiarioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelBeneficiarioLayout.createSequentialGroup()
                .add(PanelBeneficiarioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PanelBeneficiarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(separadorBeneficiario))
                    .add(PanelBeneficiarioLayout.createSequentialGroup()
                        .add(16, 16, 16)
                        .add(labBMain)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(senalaBeneficiario)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labSBenef)
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .add(PanelBeneficiarioLayout.createSequentialGroup()
                .add(166, 166, 166)
                .add(imgNBenef)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 310, Short.MAX_VALUE)
                .add(imgBBuscar)
                .add(148, 148, 148))
            .add(PanelBeneficiarioLayout.createSequentialGroup()
                .add(149, 149, 149)
                .add(labNBenef)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(labBBuscar)
                .add(217, 217, 217))
        );
        PanelBeneficiarioLayout.setVerticalGroup(
            PanelBeneficiarioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelBeneficiarioLayout.createSequentialGroup()
                .add(11, 11, 11)
                .add(PanelBeneficiarioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labBMain)
                    .add(senalaBeneficiario)
                    .add(labSBenef))
                .add(8, 8, 8)
                .add(separadorBeneficiario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(95, 95, 95)
                .add(PanelBeneficiarioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(imgNBenef)
                    .add(imgBBuscar))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PanelBeneficiarioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labNBenef)
                    .add(labBBuscar))
                .addContainerGap(163, Short.MAX_VALUE))
        );

        PanelVoluntario.setBackground(new java.awt.Color(255, 255, 255));

        labVMain.setForeground(new java.awt.Color(0, 0, 255));
        labVMain.setText("DIAKETAS");

        senalaVoluntario.setForeground(new java.awt.Color(153, 153, 153));
        senalaVoluntario.setText(">");

        labSVolunt.setText("Voluntarios");

        imgNVolunt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/vol.png"))); // NOI18N

        imgVBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/lupa.png"))); // NOI18N

        imgContab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/contabilidad.jpg"))); // NOI18N

        imgAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/images.jpg"))); // NOI18N

        labVBuscar.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labVBuscar.setText("BUSCAR");

        labAyuda.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labAyuda.setText("AYUDAS");

        labContab.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labContab.setText("CONTABILIDAD");

        org.jdesktop.layout.GroupLayout PanelVoluntarioLayout = new org.jdesktop.layout.GroupLayout(PanelVoluntario);
        PanelVoluntario.setLayout(PanelVoluntarioLayout);
        PanelVoluntarioLayout.setHorizontalGroup(
            PanelVoluntarioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelVoluntarioLayout.createSequentialGroup()
                .add(PanelVoluntarioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PanelVoluntarioLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(PanelVoluntarioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(separadorVoluntario)
                            .add(PanelVoluntarioLayout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(labVMain)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(senalaVoluntario)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(labSVolunt)
                                .add(0, 0, Short.MAX_VALUE))))
                    .add(PanelVoluntarioLayout.createSequentialGroup()
                        .add(204, 204, 204)
                        .add(PanelVoluntarioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(PanelVoluntarioLayout.createSequentialGroup()
                                .add(6, 6, 6)
                                .add(labContab)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 236, Short.MAX_VALUE)
                                .add(labAyuda)
                                .add(331, 331, 331))
                            .add(PanelVoluntarioLayout.createSequentialGroup()
                                .add(imgContab)
                                .add(208, 208, 208)
                                .add(imgAyuda)
                                .add(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
            .add(PanelVoluntarioLayout.createSequentialGroup()
                .add(51, 51, 51)
                .add(imgNVolunt)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(imgVBuscar)
                .add(119, 119, 119))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, PanelVoluntarioLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(labVBuscar)
                .add(162, 162, 162))
        );
        PanelVoluntarioLayout.setVerticalGroup(
            PanelVoluntarioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelVoluntarioLayout.createSequentialGroup()
                .add(12, 12, 12)
                .add(PanelVoluntarioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labVMain)
                    .add(senalaVoluntario)
                    .add(labSVolunt))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(separadorVoluntario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(PanelVoluntarioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(PanelVoluntarioLayout.createSequentialGroup()
                        .add(PanelVoluntarioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(imgNVolunt)
                            .add(imgVBuscar))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labVBuscar)
                        .add(12, 12, 12)
                        .add(imgContab))
                    .add(imgAyuda))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(PanelVoluntarioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(labAyuda)
                    .add(labContab))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(PanelIdentificacion, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
                .addContainerGap())
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(PanelInicio, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
                    .addContainerGap()))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(PanelSocio, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 954, Short.MAX_VALUE)
                    .addContainerGap()))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(PanelBeneficiario, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .add(PanelVoluntario, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .add(PanelIdentificacion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 476, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(65, Short.MAX_VALUE)
                    .add(PanelInicio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 476, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(64, Short.MAX_VALUE)
                    .add(PanelSocio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 477, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(65, Short.MAX_VALUE)
                    .add(PanelBeneficiario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(65, 65, 65)
                    .add(PanelVoluntario, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBeneficiario;
    private javax.swing.JPanel PanelIdentificacion;
    private javax.swing.JPanel PanelInicio;
    private javax.swing.JPanel PanelSocio;
    private javax.swing.JPanel PanelVoluntario;
    private javax.swing.JButton btConectarse;
    private javax.swing.JLabel imgAyuda;
    private javax.swing.JLabel imgBBuscar;
    private javax.swing.JLabel imgBeneficiario;
    private javax.swing.JLabel imgBolsaTrabajo;
    private javax.swing.JLabel imgContab;
    private javax.swing.JLabel imgIdent;
    private javax.swing.JLabel imgNBenef;
    private javax.swing.JLabel imgNVolunt;
    private javax.swing.JLabel imgSocio;
    private javax.swing.JLabel imgVBuscar;
    private javax.swing.JLabel imgVoluntario;
    private javax.swing.JLabel labAyuda;
    private javax.swing.JLabel labBBuscar;
    private javax.swing.JLabel labBMain;
    private javax.swing.JLabel labContab;
    private javax.swing.JLabel labNBenef;
    private javax.swing.JLabel labSBenef;
    private javax.swing.JLabel labSVolunt;
    private javax.swing.JLabel labVBuscar;
    private javax.swing.JLabel labVMain;
    private javax.swing.JLabel labelBeneficiario;
    private javax.swing.JLabel labelBolsaTrabajo;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelSocio;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JLabel labelVoluntario;
    private javax.swing.JLabel senalaBeneficiario;
    private javax.swing.JLabel senalaVoluntario;
    private javax.swing.JSeparator separadorBeneficiario;
    private javax.swing.JSeparator separadorVoluntario;
    private javax.swing.JTextField textFieldContrasena;
    private javax.swing.JTextField textFieldUsuario;
    // End of variables declaration//GEN-END:variables
	
	/**
	 * @post Muestra la vista de identificación
	 */
	public void mostrarVistaIdentificacion(){
		PanelIdentificacion.setVisible(true);
		//Todos los demas paneles se ponen a false
		PanelInicio.setVisible(false);
		PanelSocio.setVisible(false);
		PanelBeneficiario.setVisible(false);
		PanelVoluntario.setVisible(false);
	}
	
	/**
	 * @post Muestra la vista principal
	 */
	public void mostrarVistaPrincipal(){
		
		PanelInicio.setVisible(true);
		//Todos los demas paneles se ponen a false
		PanelIdentificacion.setVisible(false);
		PanelSocio.setVisible(false);
		PanelBeneficiario.setVisible(false);
		PanelVoluntario.setVisible(false);
		
	}
	
	/**
	 * @post Muestra la vista de los socios
	 */
	public void mostrarVistaSocios(){
		
		PanelSocio.setVisible(true);
		//Todos los demas paneles se ponen a false
		PanelInicio.setVisible(false);
		PanelIdentificacion.setVisible(false);
		PanelBeneficiario.setVisible(false);
		PanelVoluntario.setVisible(false);
		
	}
	
	/**
	 * @post Muestra la vista de los beneficiarios
	 */
	public void mostrarVistaBenef(){
		
		PanelBeneficiario.setVisible(true);
		//Todos los demas paneles se ponen a false
		PanelInicio.setVisible(false);
		PanelIdentificacion.setVisible(false);
		PanelSocio.setVisible(false);
		PanelVoluntario.setVisible(false);
		
	}
	
	/**
	 * @post Muestra la vista de crear nuevos beneficiarios
	 */
	public void mostrarVistaNBenef(){
		
		PanelBeneficiario.setVisible(true);
		//Todos los demas paneles se ponen a false
		PanelInicio.setVisible(false);
		PanelIdentificacion.setVisible(false);
		PanelSocio.setVisible(false);
		PanelVoluntario.setVisible(false);
		
	}
	
	/**
	 * @post Muestra la vista de buscar beneficiarios
	 */
	public void mostrarVistaBBuscar(){
		
		PanelBeneficiario.setVisible(true);
		//Todos los demas paneles se ponen a false
		PanelInicio.setVisible(false);
		PanelIdentificacion.setVisible(false);
		PanelSocio.setVisible(false);
		PanelVoluntario.setVisible(false);
		
	}
	
	/**
	 * @post Muestra la vista de los voluntarios
	 */
	public void mostrarVistaVolunt(){
		
		PanelVoluntario.setVisible(true);
		//Todos los demas paneles se ponen a false
		PanelInicio.setVisible(false);
		PanelIdentificacion.setVisible(false);
		PanelSocio.setVisible(false);
		PanelBeneficiario.setVisible(false);
		
	}
	
	/**
	 * @post Muestra la vista de creacion de voluntarios
	 */
	public void mostrarVistaNVolunt(){
		
		PanelBeneficiario.setVisible(true);
		//Todos los demas paneles se ponen a false
		PanelInicio.setVisible(false);
		PanelIdentificacion.setVisible(false);
		PanelSocio.setVisible(false);
		PanelVoluntario.setVisible(false);
		
	}
	
	/**
	 * @post Muestra la vista buscar voluntarios
	 */
	public void mostrarVistaVBuscar(){
		
		PanelBeneficiario.setVisible(true);
		//Todos los demas paneles se ponen a false
		PanelInicio.setVisible(false);
		PanelIdentificacion.setVisible(false);
		PanelSocio.setVisible(false);
		PanelVoluntario.setVisible(false);
		
	}
	
	/**
	 * @post Muestra la vista de contabilidad
	 */
	public void mostrarVistaContab(){
		
		PanelBeneficiario.setVisible(true);
		//Todos los demas paneles se ponen a false
		PanelInicio.setVisible(false);
		PanelIdentificacion.setVisible(false);
		PanelSocio.setVisible(false);
		PanelVoluntario.setVisible(false);
		
	}
	
	/**
	 * @post Muestra la vista de ayudas
	 */
	public void mostrarVistaAyuda(){
		
		PanelBeneficiario.setVisible(true);
		//Todos los demas paneles se ponen a false
		PanelInicio.setVisible(false);
		PanelIdentificacion.setVisible(false);
		PanelSocio.setVisible(false);
		PanelVoluntario.setVisible(false);
		
	}
	
	/**
	 * @post Añade listener al boton indicado
	 * @param listener
	 */
	public void anadirListenerBIdent(ActionListener listener){
		btConectarse.addActionListener(listener);
	}
	
	/**
	 * @post Añade listener al boton indicado
	 * @param listener
	 */
	public void anadirListenerImgSocios(MouseListener listener){
		imgSocio.addMouseListener(listener);
	}
	
	/**
	 * @post Añade listener al boton indicado
	 * @param listener
	 */
	public void anadirListenerImgBenef(MouseListener listener){
		imgBeneficiario.addMouseListener(listener);
	}
	
	/**
	 * @post Añade listener al boton indicado
	 * @param listener
	 */
	public void anadirListenerImgVolunt(MouseListener listener){
		imgVoluntario.addMouseListener(listener);
	}
	
	/**
	 * @post Añade listener al boton indicado
	 * @param listener
	 */
	public void anadirListenerLabBMain(MouseListener listener){
		labBMain.addMouseListener(listener);
	}
	
	/**
	 * @post Añade listener al boton indicado
	 * @param listener
	 */
	public void anadirListenerImgNBenef(MouseListener listener){
		imgNBenef.addMouseListener(listener);
	}
	
	/**
	 * @post Añade listener al boton indicado
	 * @param listener
	 */
	public void anadirListenerImgBBuscar(MouseListener listener){
		imgBBuscar.addMouseListener(listener);
	}
	
	/**
	 * @post Añade listener al boton indicado
	 * @param listener
	 */
	public void anadirListenerImgNVolunt(MouseListener listener){
		imgNVolunt.addMouseListener(listener);
	}
	
	/**
	 * @post Añade listener al boton indicado
	 * @param listener
	 */
	public void anadirListenerImgVBuscar(MouseListener listener){
		imgVBuscar.addMouseListener(listener);
	}
	
	/**
	 * @post Añade listener al boton indicado
	 * @param listener
	 */
	public void anadirListenerImgContab(MouseListener listener){
		imgContab.addMouseListener(listener);
	}
	
	/**
	 * @post Añade listener al boton indicado
	 * @param listener
	 */
	public void anadirListenerImgAyuda(MouseListener listener){
		imgAyuda.addMouseListener(listener);
	}
	
}
