package Vista;

import Controlador.ControladorPrincipal;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;

/**
 *
 * @author Jose Angel Gonzalez Molina
 */
public class VentanaPrincipal extends javax.swing.JFrame {

	private static VentanaPrincipal instancia;
        
        public static VentanaPrincipal getInstance(){
            if (instancia == null)
                instancia = new VentanaPrincipal();
            return instancia;
        }
	/**
	 * Creates new form VentanaPrincipal
	 */
	private VentanaPrincipal() {
		initComponents();
                
               System.out.print("Registrando controladores...");
                ControladorPrincipal cPrincipal = ControladorPrincipal.getInstance();
                
                
               
                /** 
                 * REGISTRAR LISTENERS PARA EL PANEL DE IDENTIFICACION
                 */
                btConectarse.addActionListener(cPrincipal);
                
                /**
                 * REGISTRAR LISTENERS PARA EL PANEL DE INICIO PRINCIPAL
                 */
                
                btBeneficiario.addActionListener(cPrincipal);
                btBolsaTrabajo.addActionListener(cPrincipal);
                btSocio.addActionListener(cPrincipal);
                btVoluntario.addActionListener(cPrincipal);
                
                System.out.println("hecho!");
                 System.out.println("Instancia de Controlador principal:" + cPrincipal);
                 
                 this.setVisible(true);
                 this.mostrarVistaIdentificacion();
                 
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelVoluntarioInicio = new javax.swing.JPanel();
        separadorVoluntario = new javax.swing.JSeparator();
        navToMainFromVoluntarios = new javax.swing.JLabel();
        senalaVoluntario = new javax.swing.JLabel();
        labSVolunt = new javax.swing.JLabel();
        btNuevoVoluntario = new javax.swing.JButton();
        btBuscar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        PanelIdentificacion = new javax.swing.JPanel();
        imgLogo = new javax.swing.JLabel();
        labelTitulo = new javax.swing.JLabel();
        labelUsuario = new javax.swing.JLabel();
        labelContrasena = new javax.swing.JLabel();
        textFieldIdUsuario = new javax.swing.JTextField();
        btConectarse = new javax.swing.JButton();
        textFieldContrasena = new javax.swing.JPasswordField();
        PanelInicio = new javax.swing.JPanel();
        btSocio = new javax.swing.JButton();
        btBeneficiario = new javax.swing.JButton();
        btVoluntario = new javax.swing.JButton();
        btBolsaTrabajo = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        panelVoluntarioDatos = new javax.swing.JPanel();
        separadorDatosVoluntario = new javax.swing.JSeparator();
        navToMainFromDatosVoluntario = new javax.swing.JLabel();
        senalaVoluntarioDatos = new javax.swing.JLabel();
        labSVolunt1 = new javax.swing.JLabel();
        navToVoluntariosFromDatosVoluntario = new javax.swing.JLabel();
        senalaVoluntarioDatos1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textNombre = new javax.swing.JTextField();
        textNIF = new javax.swing.JTextField();
        textNacionalidad = new javax.swing.JTextField();
        textNivelEstudios = new javax.swing.JTextField();
        textDomicilio = new javax.swing.JTextField();
        textLocalidad = new javax.swing.JTextField();
        textObservaciones = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        textApellidos = new javax.swing.JTextField();
        textProfesion = new javax.swing.JTextField();
        textCP = new javax.swing.JTextField();
        textTelefono = new javax.swing.JTextField();
        cbEstadoCivil = new javax.swing.JComboBox();
        textFechaNacimiento = new javax.swing.JFormattedTextField();
        btGuardar = new javax.swing.JButton();
        btBorrar = new javax.swing.JButton();
        PanelVoluntarioContabilidad = new javax.swing.JPanel();
        separadorContabilidad = new javax.swing.JSeparator();
        navToMainFromContabilidad = new javax.swing.JLabel();
        senalaBeneficiario1 = new javax.swing.JLabel();
        navToVoluntariosFromContabilidad = new javax.swing.JLabel();
        senalaBeneficiario2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelListaGastos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelListaIngresos = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        fieldFechaInicio = new javax.swing.JFormattedTextField();
        fieldFechaFin = new javax.swing.JFormattedTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnObtenerContabilidad = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        cuadroBalance = new javax.swing.JTextField();
        PanelBeneficiarioInicio = new javax.swing.JPanel();
        separadorBeneficiario = new javax.swing.JSeparator();
        navToMainFromBeneficiarios = new javax.swing.JLabel();
        senalaBeneficiario = new javax.swing.JLabel();
        labSBenef = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Diaketas Manage");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(135, 170, 235));
        setBounds(new java.awt.Rectangle(0, 0, 888, 450));
        setMaximumSize(new java.awt.Dimension(888, 450));
        setMinimumSize(new java.awt.Dimension(888, 450));
        setResizable(false);

        PanelVoluntarioInicio.setBackground(new java.awt.Color(255, 255, 255));
        PanelVoluntarioInicio.setMaximumSize(new java.awt.Dimension(888, 450));
        PanelVoluntarioInicio.setMinimumSize(new java.awt.Dimension(888, 450));
        PanelVoluntarioInicio.setPreferredSize(new java.awt.Dimension(888, 450));
        PanelVoluntarioInicio.setSize(new java.awt.Dimension(888, 450));

        navToMainFromVoluntarios.setForeground(new java.awt.Color(0, 0, 255));
        navToMainFromVoluntarios.setText("DIAKETAS");
        navToMainFromVoluntarios.setToolTipText("navToMainFromVoluntarios");

        senalaVoluntario.setForeground(new java.awt.Color(153, 153, 153));
        senalaVoluntario.setText(">");

        labSVolunt.setText("Voluntarios");

        btNuevoVoluntario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/vol.png"))); // NOI18N
        btNuevoVoluntario.setActionCommand("nuevoVoluntario");

        btBuscar.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/lupa.png"))); // NOI18N
        btBuscar.setText("BUSCAR");
        btBuscar.setActionCommand("buscarVoluntario");
        btBuscar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btBuscar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/contabilidad.jpg"))); // NOI18N
        jButton3.setText("Contabilidad");
        jButton3.setActionCommand("contabilidad");
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton4.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/images.jpg"))); // NOI18N
        jButton4.setText("AYUDAS");
        jButton4.setActionCommand("ayudas");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        org.jdesktop.layout.GroupLayout PanelVoluntarioInicioLayout = new org.jdesktop.layout.GroupLayout(PanelVoluntarioInicio);
        PanelVoluntarioInicio.setLayout(PanelVoluntarioInicioLayout);
        PanelVoluntarioInicioLayout.setHorizontalGroup(
            PanelVoluntarioInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelVoluntarioInicioLayout.createSequentialGroup()
                .addContainerGap()
                .add(PanelVoluntarioInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(separadorVoluntario)
                    .add(PanelVoluntarioInicioLayout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(navToMainFromVoluntarios)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(senalaVoluntario)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labSVolunt)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, PanelVoluntarioInicioLayout.createSequentialGroup()
                        .add(PanelVoluntarioInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(PanelVoluntarioInicioLayout.createSequentialGroup()
                                .add(87, 87, 87)
                                .add(btNuevoVoluntario))
                            .add(PanelVoluntarioInicioLayout.createSequentialGroup()
                                .add(213, 213, 213)
                                .add(jButton3)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 91, Short.MAX_VALUE)
                        .add(PanelVoluntarioInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jButton4)
                            .add(btBuscar))
                        .add(145, 145, 145)))
                .addContainerGap())
        );
        PanelVoluntarioInicioLayout.setVerticalGroup(
            PanelVoluntarioInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelVoluntarioInicioLayout.createSequentialGroup()
                .addContainerGap()
                .add(PanelVoluntarioInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(navToMainFromVoluntarios)
                    .add(senalaVoluntario)
                    .add(labSVolunt))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(separadorVoluntario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(PanelVoluntarioInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PanelVoluntarioInicioLayout.createSequentialGroup()
                        .add(36, 36, 36)
                        .add(btNuevoVoluntario))
                    .add(PanelVoluntarioInicioLayout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(btBuscar)))
                .add(9, 9, 9)
                .add(PanelVoluntarioInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PanelVoluntarioInicioLayout.createSequentialGroup()
                        .add(jButton3)
                        .add(28, 28, 28))
                    .add(PanelVoluntarioInicioLayout.createSequentialGroup()
                        .add(28, 28, 28)
                        .add(jButton4)))
                .add(27, 27, 27))
        );

        PanelIdentificacion.setBackground(new java.awt.Color(255, 254, 254));
        PanelIdentificacion.setMaximumSize(new java.awt.Dimension(888, 450));
        PanelIdentificacion.setMinimumSize(new java.awt.Dimension(888, 450));
        PanelIdentificacion.setPreferredSize(new java.awt.Dimension(888, 450));
        PanelIdentificacion.setSize(new java.awt.Dimension(888, 450));

        imgLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/Acceso_Usuarios.jpg"))); // NOI18N

        labelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 0, 0));
        labelTitulo.setText("BIENVENIDO A DIAKETAS");

        labelUsuario.setText("USUARIO");

        labelContrasena.setText("CONTRASEÑA");

        textFieldIdUsuario.setText("Usuario");

        btConectarse.setText("Entrar");
        btConectarse.setActionCommand("accionLogin");

        textFieldContrasena.setText("jPasswordField1");

        org.jdesktop.layout.GroupLayout PanelIdentificacionLayout = new org.jdesktop.layout.GroupLayout(PanelIdentificacion);
        PanelIdentificacion.setLayout(PanelIdentificacionLayout);
        PanelIdentificacionLayout.setHorizontalGroup(
            PanelIdentificacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelIdentificacionLayout.createSequentialGroup()
                .add(55, 55, 55)
                .add(PanelIdentificacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PanelIdentificacionLayout.createSequentialGroup()
                        .add(423, 423, 423)
                        .add(PanelIdentificacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(labelUsuario)
                            .add(labelContrasena))
                        .add(25, 25, 25)
                        .add(PanelIdentificacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(PanelIdentificacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(textFieldIdUsuario)
                                .add(textFieldContrasena, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(btConectarse)))
                    .add(imgLogo)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, labelTitulo))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        PanelIdentificacionLayout.setVerticalGroup(
            PanelIdentificacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelIdentificacionLayout.createSequentialGroup()
                .add(64, 64, 64)
                .add(PanelIdentificacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(imgLogo)
                    .add(PanelIdentificacionLayout.createSequentialGroup()
                        .add(labelTitulo)
                        .add(135, 135, 135)
                        .add(PanelIdentificacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(labelUsuario)
                            .add(textFieldIdUsuario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(PanelIdentificacionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(labelContrasena)
                            .add(textFieldContrasena, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(btConectarse)))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        PanelInicio.setBackground(new java.awt.Color(255, 255, 255));
        PanelInicio.setMaximumSize(new java.awt.Dimension(888, 450));
        PanelInicio.setPreferredSize(new java.awt.Dimension(888, 450));
        PanelInicio.setSize(new java.awt.Dimension(888, 450));

        btSocio.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btSocio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/socio.png"))); // NOI18N
        btSocio.setText("SOCIOS");
        btSocio.setToolTipText("Acceso a Socios");
        btSocio.setActionCommand("entrarAPanelSocios");
        btSocio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btSocio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btSocio.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btSocio.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btBeneficiario.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btBeneficiario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/bene.png"))); // NOI18N
        btBeneficiario.setText("BENEFICIARIOS");
        btBeneficiario.setActionCommand("entrarAPanelBeneficiarios");
        btBeneficiario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btBeneficiario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btVoluntario.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btVoluntario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/imgVolunt.jpg"))); // NOI18N
        btVoluntario.setText("VOLUNTARIOS");
        btVoluntario.setActionCommand("entrarAPanelVoluntarios");
        btVoluntario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btVoluntario.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btBolsaTrabajo.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        btBolsaTrabajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/imgBolsa.jpg"))); // NOI18N
        btBolsaTrabajo.setText("BOLSA DE TRABAJO");
        btBolsaTrabajo.setActionCommand("entrarAPanelBolsaTrabajo");
        btBolsaTrabajo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btBolsaTrabajo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel21.setText("PANEL PRINCIPAL");

        org.jdesktop.layout.GroupLayout PanelInicioLayout = new org.jdesktop.layout.GroupLayout(PanelInicio);
        PanelInicio.setLayout(PanelInicioLayout);
        PanelInicioLayout.setHorizontalGroup(
            PanelInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelInicioLayout.createSequentialGroup()
                .add(PanelInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PanelInicioLayout.createSequentialGroup()
                        .add(161, 161, 161)
                        .add(btVoluntario))
                    .add(PanelInicioLayout.createSequentialGroup()
                        .add(150, 150, 150)
                        .add(btSocio)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 232, Short.MAX_VALUE)
                .add(PanelInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, PanelInicioLayout.createSequentialGroup()
                        .add(btBeneficiario)
                        .add(125, 125, 125))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, PanelInicioLayout.createSequentialGroup()
                        .add(btBolsaTrabajo)
                        .add(159, 159, 159))))
            .add(PanelInicioLayout.createSequentialGroup()
                .add(29, 29, 29)
                .add(jLabel21)
                .addContainerGap())
        );
        PanelInicioLayout.setVerticalGroup(
            PanelInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelInicioLayout.createSequentialGroup()
                .add(PanelInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, PanelInicioLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(btBeneficiario)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED))
                    .add(PanelInicioLayout.createSequentialGroup()
                        .add(26, 26, 26)
                        .add(jLabel21)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 21, Short.MAX_VALUE)
                        .add(btSocio)
                        .add(20, 20, 20)))
                .add(PanelInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(btVoluntario)
                    .add(btBolsaTrabajo))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        panelVoluntarioDatos.setBackground(new java.awt.Color(255, 255, 255));
        panelVoluntarioDatos.setMaximumSize(new java.awt.Dimension(888, 450));
        panelVoluntarioDatos.setMinimumSize(new java.awt.Dimension(888, 450));
        panelVoluntarioDatos.setPreferredSize(new java.awt.Dimension(888, 450));
        panelVoluntarioDatos.setSize(new java.awt.Dimension(888, 450));

        navToMainFromDatosVoluntario.setForeground(new java.awt.Color(0, 0, 255));
        navToMainFromDatosVoluntario.setText("DIAKETAS");
        navToMainFromDatosVoluntario.setToolTipText("navToMainFromDatosVoluntario");

        senalaVoluntarioDatos.setForeground(new java.awt.Color(153, 153, 153));
        senalaVoluntarioDatos.setText(">");

        labSVolunt1.setText("Datos Voluntario");

        navToVoluntariosFromDatosVoluntario.setForeground(new java.awt.Color(0, 0, 255));
        navToVoluntariosFromDatosVoluntario.setText("Voluntario");
        navToVoluntariosFromDatosVoluntario.setToolTipText("navToVoluntariosFromDatosVoluntario");

        senalaVoluntarioDatos1.setForeground(new java.awt.Color(153, 153, 153));
        senalaVoluntarioDatos1.setText(">");

        jLabel2.setText("Nombre");

        jLabel3.setText("NIF/DNI/Pasaporte");

        jLabel4.setText("Nacionalidad");

        jLabel5.setText("Nivel de estudios");

        jLabel6.setText("Domicilio");

        jLabel7.setText("Localidad");

        jLabel8.setText("Observaciones");

        jLabel1.setText("Apellidos");

        jLabel9.setText("Nacido el");

        jLabel10.setText("Estado Civil");

        jLabel11.setText("Profesión");

        jLabel12.setText("CP");

        jLabel13.setText("Teléfono");

        cbEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Casado", "Soltero", "NS/NC" }));

        textFechaNacimiento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        btGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/save_f2.png"))); // NOI18N
        btGuardar.setActionCommand("guardarDatosVoluntario");

        btBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/limpiar.png"))); // NOI18N
        btBorrar.setActionCommand("borrarDatosVoluntario");

        org.jdesktop.layout.GroupLayout panelVoluntarioDatosLayout = new org.jdesktop.layout.GroupLayout(panelVoluntarioDatos);
        panelVoluntarioDatos.setLayout(panelVoluntarioDatosLayout);
        panelVoluntarioDatosLayout.setHorizontalGroup(
            panelVoluntarioDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelVoluntarioDatosLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelVoluntarioDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panelVoluntarioDatosLayout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(navToMainFromDatosVoluntario)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(senalaVoluntarioDatos)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(navToVoluntariosFromDatosVoluntario)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(senalaVoluntarioDatos1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labSVolunt1)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(separadorDatosVoluntario))
                .addContainerGap())
            .add(panelVoluntarioDatosLayout.createSequentialGroup()
                .add(39, 39, 39)
                .add(panelVoluntarioDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(jLabel3)
                    .add(jLabel4)
                    .add(jLabel5)
                    .add(jLabel6)
                    .add(jLabel7)
                    .add(jLabel8))
                .add(112, 112, 112)
                .add(panelVoluntarioDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(textObservaciones, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(panelVoluntarioDatosLayout.createSequentialGroup()
                        .add(panelVoluntarioDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, panelVoluntarioDatosLayout.createSequentialGroup()
                                .add(68, 68, 68)
                                .add(btGuardar))
                            .add(panelVoluntarioDatosLayout.createSequentialGroup()
                                .add(textLocalidad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jLabel13))
                            .add(panelVoluntarioDatosLayout.createSequentialGroup()
                                .add(textDomicilio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jLabel12))
                            .add(panelVoluntarioDatosLayout.createSequentialGroup()
                                .add(textNivelEstudios, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jLabel11))
                            .add(panelVoluntarioDatosLayout.createSequentialGroup()
                                .add(textNacionalidad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jLabel10))
                            .add(panelVoluntarioDatosLayout.createSequentialGroup()
                                .add(textNIF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jLabel9))
                            .add(panelVoluntarioDatosLayout.createSequentialGroup()
                                .add(textNombre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 172, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(68, 68, 68)
                                .add(jLabel1)))
                        .add(panelVoluntarioDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(panelVoluntarioDatosLayout.createSequentialGroup()
                                .add(2, 2, 2)
                                .add(btBorrar))
                            .add(panelVoluntarioDatosLayout.createSequentialGroup()
                                .add(50, 50, 50)
                                .add(panelVoluntarioDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(textApellidos)
                                    .add(textFechaNacimiento)
                                    .add(textProfesion)
                                    .add(textCP)
                                    .add(textTelefono, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 172, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(cbEstadoCivil, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))))
                .add(0, 96, Short.MAX_VALUE))
        );

        panelVoluntarioDatosLayout.linkSize(new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        panelVoluntarioDatosLayout.linkSize(new java.awt.Component[] {textApellidos, textCP, textDomicilio, textFechaNacimiento, textLocalidad, textNIF, textNacionalidad, textNivelEstudios, textNombre, textObservaciones, textProfesion, textTelefono}, org.jdesktop.layout.GroupLayout.HORIZONTAL);

        panelVoluntarioDatosLayout.setVerticalGroup(
            panelVoluntarioDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelVoluntarioDatosLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelVoluntarioDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(navToMainFromDatosVoluntario)
                    .add(senalaVoluntarioDatos)
                    .add(labSVolunt1)
                    .add(navToVoluntariosFromDatosVoluntario)
                    .add(senalaVoluntarioDatos1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(separadorDatosVoluntario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 43, Short.MAX_VALUE)
                .add(panelVoluntarioDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(textNombre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1)
                    .add(textApellidos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(12, 12, 12)
                .add(panelVoluntarioDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(textNIF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel9)
                    .add(textFechaNacimiento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(9, 9, 9)
                .add(panelVoluntarioDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(textNacionalidad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel10)
                    .add(cbEstadoCivil, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelVoluntarioDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(textNivelEstudios, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5)
                    .add(jLabel11)
                    .add(textProfesion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelVoluntarioDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(textDomicilio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel12)
                    .add(textCP, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelVoluntarioDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(textLocalidad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel13)
                    .add(textTelefono, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelVoluntarioDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(textObservaciones, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 16, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(39, 39, 39)
                .add(panelVoluntarioDatosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btGuardar)
                    .add(btBorrar))
                .add(44, 44, 44))
        );

        panelVoluntarioDatosLayout.linkSize(new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5, jLabel6, jLabel7, jLabel8}, org.jdesktop.layout.GroupLayout.VERTICAL);

        PanelVoluntarioContabilidad.setBackground(new java.awt.Color(255, 255, 255));
        PanelVoluntarioContabilidad.setMaximumSize(new java.awt.Dimension(888, 450));
        PanelVoluntarioContabilidad.setPreferredSize(new java.awt.Dimension(888, 450));
        PanelVoluntarioContabilidad.setSize(new java.awt.Dimension(888, 450));

        navToMainFromContabilidad.setFont(new java.awt.Font("Lucida Sans", 0, 13)); // NOI18N
        navToMainFromContabilidad.setForeground(new java.awt.Color(0, 0, 255));
        navToMainFromContabilidad.setText("DIAKETAS");
        navToMainFromContabilidad.setToolTipText("navToMainFromContabilidad");

        senalaBeneficiario1.setForeground(new java.awt.Color(153, 153, 153));
        senalaBeneficiario1.setText(">");

        navToVoluntariosFromContabilidad.setForeground(new java.awt.Color(0, 0, 255));
        navToVoluntariosFromContabilidad.setText("Voluntarios");
        navToVoluntariosFromContabilidad.setToolTipText("navToVoluntariosFromContabilidad");

        senalaBeneficiario2.setForeground(new java.awt.Color(153, 153, 153));
        senalaBeneficiario2.setText(">");

        jLabel14.setText("Contabilidad");

        panelListaGastos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Ingreso", "Dni", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(panelListaGastos);

        panelListaIngresos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha", "Gasto", "Dni", ""
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(panelListaIngresos);

        jLabel15.setText("Contabilidad");

        fieldFechaInicio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        fieldFechaFin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jLabel16.setText("Fecha inicio");

        jLabel17.setText("Fecha fin");

        jLabel18.setText("Listado de ingresos");

        jLabel19.setText("Listado de gastos");

        btnObtenerContabilidad.setText("Obtener Contabilidad");
        btnObtenerContabilidad.setActionCommand("obtenerContabilidad");

        jLabel20.setText("Balance");

        org.jdesktop.layout.GroupLayout PanelVoluntarioContabilidadLayout = new org.jdesktop.layout.GroupLayout(PanelVoluntarioContabilidad);
        PanelVoluntarioContabilidad.setLayout(PanelVoluntarioContabilidadLayout);
        PanelVoluntarioContabilidadLayout.setHorizontalGroup(
            PanelVoluntarioContabilidadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelVoluntarioContabilidadLayout.createSequentialGroup()
                .add(PanelVoluntarioContabilidadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PanelVoluntarioContabilidadLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(separadorContabilidad))
                    .add(PanelVoluntarioContabilidadLayout.createSequentialGroup()
                        .add(16, 16, 16)
                        .add(navToMainFromContabilidad)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(senalaBeneficiario1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(navToVoluntariosFromContabilidad)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(senalaBeneficiario2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel14)
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .add(PanelVoluntarioContabilidadLayout.createSequentialGroup()
                .add(14, 14, 14)
                .add(PanelVoluntarioContabilidadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel18)
                    .add(PanelVoluntarioContabilidadLayout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 332, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(PanelVoluntarioContabilidadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(jLabel15)
                            .add(jLabel17)
                            .add(jLabel16)
                            .add(fieldFechaFin)
                            .add(fieldFechaInicio)
                            .add(btnObtenerContabilidad, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(jLabel20)
                            .add(cuadroBalance))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(PanelVoluntarioContabilidadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel19)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 348, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(16, 16, 16))
        );
        PanelVoluntarioContabilidadLayout.setVerticalGroup(
            PanelVoluntarioContabilidadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelVoluntarioContabilidadLayout.createSequentialGroup()
                .add(11, 11, 11)
                .add(PanelVoluntarioContabilidadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(navToMainFromContabilidad)
                    .add(senalaBeneficiario1)
                    .add(navToVoluntariosFromContabilidad)
                    .add(senalaBeneficiario2)
                    .add(jLabel14))
                .add(8, 8, 8)
                .add(separadorContabilidad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(PanelVoluntarioContabilidadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel18)
                    .add(jLabel19))
                .add(9, 9, 9)
                .add(PanelVoluntarioContabilidadLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(PanelVoluntarioContabilidadLayout.createSequentialGroup()
                        .add(jLabel15)
                        .add(18, 18, 18)
                        .add(jLabel16)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(fieldFechaInicio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(12, 12, 12)
                        .add(jLabel17)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(fieldFechaFin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(49, 49, 49)
                        .add(btnObtenerContabilidad)
                        .add(47, 47, 47)
                        .add(jLabel20)
                        .add(18, 18, 18)
                        .add(cuadroBalance, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        PanelBeneficiarioInicio.setBackground(new java.awt.Color(255, 255, 255));
        PanelBeneficiarioInicio.setMaximumSize(new java.awt.Dimension(888, 450));
        PanelBeneficiarioInicio.setPreferredSize(new java.awt.Dimension(888, 450));
        PanelBeneficiarioInicio.setSize(new java.awt.Dimension(888, 450));

        navToMainFromBeneficiarios.setFont(new java.awt.Font("Lucida Sans", 0, 13)); // NOI18N
        navToMainFromBeneficiarios.setForeground(new java.awt.Color(0, 0, 255));
        navToMainFromBeneficiarios.setText("DIAKETAS");
        navToMainFromBeneficiarios.setToolTipText("navToMainFromBeneficiarios");

        senalaBeneficiario.setForeground(new java.awt.Color(153, 153, 153));
        senalaBeneficiario.setText(">");

        labSBenef.setText("Beneficiarios");

        jButton1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/usu.png"))); // NOI18N
        jButton1.setText("NUEVO BENEFICIARIO");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jButton2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/images/lupa (1).png"))); // NOI18N
        jButton2.setText("BUSCAR");
        jButton2.setActionCommand("buscarBeneficiario");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        org.jdesktop.layout.GroupLayout PanelBeneficiarioInicioLayout = new org.jdesktop.layout.GroupLayout(PanelBeneficiarioInicio);
        PanelBeneficiarioInicio.setLayout(PanelBeneficiarioInicioLayout);
        PanelBeneficiarioInicioLayout.setHorizontalGroup(
            PanelBeneficiarioInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelBeneficiarioInicioLayout.createSequentialGroup()
                .add(PanelBeneficiarioInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(PanelBeneficiarioInicioLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(separadorBeneficiario))
                    .add(PanelBeneficiarioInicioLayout.createSequentialGroup()
                        .add(16, 16, 16)
                        .add(navToMainFromBeneficiarios)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(senalaBeneficiario)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labSBenef)
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .add(PanelBeneficiarioInicioLayout.createSequentialGroup()
                .add(194, 194, 194)
                .add(jButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 82, Short.MAX_VALUE)
                .add(jButton2)
                .add(223, 223, 223))
        );
        PanelBeneficiarioInicioLayout.setVerticalGroup(
            PanelBeneficiarioInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(PanelBeneficiarioInicioLayout.createSequentialGroup()
                .add(11, 11, 11)
                .add(PanelBeneficiarioInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(navToMainFromBeneficiarios)
                    .add(senalaBeneficiario)
                    .add(labSBenef))
                .add(8, 8, 8)
                .add(separadorBeneficiario, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(118, 118, 118)
                .add(PanelBeneficiarioInicioLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButton1)
                    .add(jButton2))
                .addContainerGap(104, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(PanelVoluntarioInicio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(PanelIdentificacion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(PanelInicio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(panelVoluntarioDatos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(PanelVoluntarioContabilidad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(PanelBeneficiarioInicio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(PanelVoluntarioInicio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(PanelIdentificacion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(PanelInicio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(panelVoluntarioDatos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(PanelVoluntarioContabilidad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(PanelBeneficiarioInicio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBeneficiarioInicio;
    private javax.swing.JPanel PanelIdentificacion;
    private javax.swing.JPanel PanelInicio;
    private javax.swing.JPanel PanelVoluntarioContabilidad;
    private javax.swing.JPanel PanelVoluntarioInicio;
    private javax.swing.JButton btBeneficiario;
    private javax.swing.JButton btBolsaTrabajo;
    private javax.swing.JButton btBorrar;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btConectarse;
    private javax.swing.JButton btGuardar;
    private javax.swing.JButton btNuevoVoluntario;
    private javax.swing.JButton btSocio;
    private javax.swing.JButton btVoluntario;
    private javax.swing.JButton btnObtenerContabilidad;
    private javax.swing.JComboBox cbEstadoCivil;
    private javax.swing.JTextField cuadroBalance;
    private javax.swing.JFormattedTextField fieldFechaFin;
    private javax.swing.JFormattedTextField fieldFechaInicio;
    private javax.swing.JLabel imgLogo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labSBenef;
    private javax.swing.JLabel labSVolunt;
    private javax.swing.JLabel labSVolunt1;
    private javax.swing.JLabel labelContrasena;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JLabel navToMainFromBeneficiarios;
    private javax.swing.JLabel navToMainFromContabilidad;
    private javax.swing.JLabel navToMainFromDatosVoluntario;
    private javax.swing.JLabel navToMainFromVoluntarios;
    private javax.swing.JLabel navToVoluntariosFromContabilidad;
    private javax.swing.JLabel navToVoluntariosFromDatosVoluntario;
    private javax.swing.JTable panelListaGastos;
    private javax.swing.JTable panelListaIngresos;
    private javax.swing.JPanel panelVoluntarioDatos;
    private javax.swing.JLabel senalaBeneficiario;
    private javax.swing.JLabel senalaBeneficiario1;
    private javax.swing.JLabel senalaBeneficiario2;
    private javax.swing.JLabel senalaVoluntario;
    private javax.swing.JLabel senalaVoluntarioDatos;
    private javax.swing.JLabel senalaVoluntarioDatos1;
    private javax.swing.JSeparator separadorBeneficiario;
    private javax.swing.JSeparator separadorContabilidad;
    private javax.swing.JSeparator separadorDatosVoluntario;
    private javax.swing.JSeparator separadorVoluntario;
    private javax.swing.JTextField textApellidos;
    private javax.swing.JTextField textCP;
    private javax.swing.JTextField textDomicilio;
    private javax.swing.JFormattedTextField textFechaNacimiento;
    private javax.swing.JPasswordField textFieldContrasena;
    private javax.swing.JTextField textFieldIdUsuario;
    private javax.swing.JTextField textLocalidad;
    private javax.swing.JTextField textNIF;
    private javax.swing.JTextField textNacionalidad;
    private javax.swing.JTextField textNivelEstudios;
    private javax.swing.JTextField textNombre;
    private javax.swing.JTextField textObservaciones;
    private javax.swing.JTextField textProfesion;
    private javax.swing.JTextField textTelefono;
    // End of variables declaration//GEN-END:variables
	
	/**
	 * @post Muestra la vista de identificación
	 */
	public void mostrarVistaIdentificacion(){
		PanelIdentificacion.setVisible(true);
		//Todos los demas paneles se ponen a false
		PanelInicio.setVisible(false);
		
		PanelBeneficiarioInicio.setVisible(false);
		PanelVoluntarioInicio.setVisible(false);
                panelVoluntarioDatos.setVisible(false);
                PanelVoluntarioContabilidad.setVisible(false);
	}
	
	/**
	 * @post Muestra la vista principal
	 */
	public void mostrarVistaPrincipal(){
		
		PanelInicio.setVisible(true);
		//Todos los demas paneles se ponen a false
		PanelIdentificacion.setVisible(false);
		
		PanelBeneficiarioInicio.setVisible(false);
		PanelVoluntarioInicio.setVisible(false);
                panelVoluntarioDatos.setVisible(false);
		PanelVoluntarioContabilidad.setVisible(false);
	}
	
	/**
	 * @post Muestra la vista de los beneficiarios
	 */
	public void mostrarVistaBenef(){
		
		PanelBeneficiarioInicio.setVisible(true);
		//Todos los demas paneles se ponen a false
		PanelInicio.setVisible(false);
		PanelIdentificacion.setVisible(false);
		
		PanelVoluntarioInicio.setVisible(false);
                panelVoluntarioDatos.setVisible(false);
		PanelVoluntarioContabilidad.setVisible(false);
	}
	
	/**
	 * @post Muestra la vista de crear nuevos beneficiarios
	 */
	public void mostrarVistaNBenef(){
		
		PanelBeneficiarioInicio.setVisible(true);
		//Todos los demas paneles se ponen a false
		PanelInicio.setVisible(false);
		PanelIdentificacion.setVisible(false);
		
		PanelVoluntarioInicio.setVisible(false);
                panelVoluntarioDatos.setVisible(false);
		PanelVoluntarioContabilidad.setVisible(false);
	}
	
	/**
	 * @post Muestra la vista de buscar beneficiarios
	 */
	public void mostrarVistaBBuscar(){
		
		PanelBeneficiarioInicio.setVisible(true);
		//Todos los demas paneles se ponen a false
		PanelInicio.setVisible(false);
		PanelIdentificacion.setVisible(false);
		
		PanelVoluntarioInicio.setVisible(false);
                panelVoluntarioDatos.setVisible(false);
		PanelVoluntarioContabilidad.setVisible(false);
	}
	
	/**
	 * @post Muestra la vista de los voluntarios
	 */
	public void mostrarVistaVolunt(){
		
		PanelVoluntarioInicio.setVisible(true);
		//Todos los demas paneles se ponen a false
		PanelInicio.setVisible(false);
		PanelIdentificacion.setVisible(false);
		
		PanelBeneficiarioInicio.setVisible(false);
                panelVoluntarioDatos.setVisible(false);
		PanelVoluntarioContabilidad.setVisible(false);
	}
	
	/**
	 * @post Muestra la vista de creacion de voluntarios
	 */
	public void mostrarVistaNVolunt(){
		
		PanelBeneficiarioInicio.setVisible(true);
		//Todos los demas paneles se ponen a false
		PanelInicio.setVisible(false);
		PanelIdentificacion.setVisible(false);
		
		PanelVoluntarioInicio.setVisible(false);
		panelVoluntarioDatos.setVisible(false);
                PanelVoluntarioContabilidad.setVisible(false);
	}
	
	/**
	 * @post Muestra la vista buscar voluntarios
	 */
	public void mostrarVistaVBuscar(){
		
		PanelBeneficiarioInicio.setVisible(true);
		//Todos los demas paneles se ponen a false
		PanelInicio.setVisible(false);
		PanelIdentificacion.setVisible(false);
		
		PanelVoluntarioInicio.setVisible(false);
                panelVoluntarioDatos.setVisible(false);
		PanelVoluntarioContabilidad.setVisible(false);
	}
	
	/**
	 * @post Muestra la vista de contabilidad
	 */
	public void mostrarVistaContab(){
		
		PanelVoluntarioContabilidad.setVisible(true);
		//Todos los demas paneles se ponen a false
                panelVoluntarioDatos.setVisible(false); 
                PanelBeneficiarioInicio.setVisible(false);
		PanelInicio.setVisible(false);
		PanelIdentificacion.setVisible(false);
		
		PanelVoluntarioInicio.setVisible(false);
	}
	
	/**
	 * @post Muestra la vista de ayudas
	 */
	public void mostrarVistaAyuda(){
		
		PanelBeneficiarioInicio.setVisible(true);
		//Todos los demas paneles se ponen a false
		PanelInicio.setVisible(false);
		PanelIdentificacion.setVisible(false);
		
		PanelVoluntarioInicio.setVisible(false);
                panelVoluntarioDatos.setVisible(false);
                PanelVoluntarioContabilidad.setVisible(false);
	}
        
        /**
	 * @post Muestra la vista de datos de Voluntarios
	 */
	public void mostrarVistaDatosVoluntarios(){
		
                panelVoluntarioDatos.setVisible(true); 
		//Todos los demas paneles se ponen a false
                PanelBeneficiarioInicio.setVisible(false);
		PanelInicio.setVisible(false);
		PanelIdentificacion.setVisible(false);
		
		PanelVoluntarioInicio.setVisible(false);
                PanelVoluntarioContabilidad.setVisible(false);
	}
        
  
        
}
